version: '3.8'
services:

    backend:
        container_name: mozio_be
        build: 
          context: .
          dockerfile: Dockerfile.dev
        volumes: 
          - .:/usr/src/app/
          - ipython_data_local:/root/.ipython/profile_default
        ports: 
          - "8008:8008" # Django app ports
          - "4004:4004" # Django debugger ports
        env_file: 
          - .env
        restart: always
        depends_on: 
          - db
        tty: true
  
    database:
        container_name: mozio_db
        image: postgis/postgis:12-3.2-alpine
        restart: unless-stopped
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        env_file:
        - .env

volumes:
    postgres_data:
    ipython_data_local: {}